/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecarep.Views.Telefonos;

import mecarep.Views.PanelPrincipal;
import mecarep.Views.Vehiculos.RegistrarVehiculo;

/**
 *
 * @author USER
 */
public class ActTelefonos extends javax.swing.JFrame {

    /**
     * Creates new form ActTelefonos
     */
    public ActTelefonos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        txtCodEmp = new javax.swing.JTextField();
        lblCel4 = new javax.swing.JLabel();
        lblCel1 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        lblCel3 = new javax.swing.JLabel();
        txtTelefono2 = new javax.swing.JTextField();
        lblCel5 = new javax.swing.JLabel();
        txtTelefono3 = new javax.swing.JTextField();
        lblCel2 = new javax.swing.JLabel();
        txtTelefono4 = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        bgBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Actualizar Telefonos");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        lblCel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel.setForeground(new java.awt.Color(255, 255, 255));
        lblCel.setText("ID Empleado:");
        getContentPane().add(lblCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        txtCodEmp.setToolTipText("");
        getContentPane().add(txtCodEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 220, -1));

        lblCel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel4.setForeground(new java.awt.Color(255, 255, 255));
        lblCel4.setText("Actualizar: ");
        getContentPane().add(lblCel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        lblCel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel1.setForeground(new java.awt.Color(255, 255, 255));
        lblCel1.setText("Teléfono 1:");
        getContentPane().add(lblCel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        getContentPane().add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 220, -1));

        lblCel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel3.setForeground(new java.awt.Color(255, 255, 255));
        lblCel3.setText("Teléfono 2:");
        getContentPane().add(lblCel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        getContentPane().add(txtTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, -1));

        lblCel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel5.setForeground(new java.awt.Color(255, 255, 255));
        lblCel5.setText("Teléfono 3:");
        getContentPane().add(lblCel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        getContentPane().add(txtTelefono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 220, -1));

        lblCel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel2.setForeground(new java.awt.Color(255, 255, 255));
        lblCel2.setText("Teléfono 4:");
        getContentPane().add(lblCel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));
        getContentPane().add(txtTelefono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 220, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 102, 204));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setToolTipText("");
        btnActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 120, 30));

        btnRegresar.setBackground(new java.awt.Color(153, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Cancelar");
        btnRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 120, 30));

        bgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        getContentPane().add(bgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        RegistrarVehiculo nw = new RegistrarVehiculo();
        nw.setVisible(true);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        PanelPrincipal nw = new PanelPrincipal();
        nw.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActTelefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActTelefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActTelefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActTelefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActTelefonos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgBack;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCel1;
    private javax.swing.JLabel lblCel2;
    private javax.swing.JLabel lblCel3;
    private javax.swing.JLabel lblCel4;
    private javax.swing.JLabel lblCel5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCodEmp;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    private javax.swing.JTextField txtTelefono3;
    private javax.swing.JTextField txtTelefono4;
    // End of variables declaration//GEN-END:variables
}
