/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecarep.Views.Telefonos;

import javax.swing.JOptionPane;
import mecarep.Controlers.Validaciones;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import mecarep.Controlers.ControladorTelefonoEmpleado;
import mecarep.Controlers.Validaciones;
import mecarep.Models.Empleado;
import mecarep.Models.TelefonoEmpleado;

/**
 *
 * @author USER
 */
public class CreateTelefono extends javax.swing.JFrame {

    /**
     * Creates new form CreateTelefono
     */
    ControladorTelefonoEmpleado tabla = new ControladorTelefonoEmpleado();

    public CreateTelefono() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        cmbTaller = new javax.swing.JComboBox<>();
        lblCel1 = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        lblCel2 = new javax.swing.JLabel();
        txtTelefonoNuevo = new javax.swing.JTextField();
        btnCancelarTel = new javax.swing.JButton();
        btnGuardarTel = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        bgBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Registrar Nuevo Telefono");
        lblTitle.setToolTipText("");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        cmbTaller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "T001", "T002" }));
        cmbTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTallerActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 190, -1));

        lblCel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel1.setForeground(new java.awt.Color(255, 255, 255));
        lblCel1.setText("Taller:");
        getContentPane().add(lblCel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        lblCel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel.setForeground(new java.awt.Color(255, 255, 255));
        lblCel.setText("ID Empleado:");
        getContentPane().add(lblCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        lblCel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel2.setForeground(new java.awt.Color(255, 255, 255));
        lblCel2.setText("Telefono: ");
        getContentPane().add(lblCel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));
        getContentPane().add(txtTelefonoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 180, -1));

        btnCancelarTel.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelarTel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCancelarTel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarTel.setText("Cancelar");
        btnCancelarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, 40));

        btnGuardarTel.setBackground(new java.awt.Color(0, 102, 204));
        btnGuardarTel.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnGuardarTel.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarTel.setText("Guardar");
        btnGuardarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTelActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 120, 40));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 150, 20));

        bgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        getContentPane().add(bgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTallerActionPerformed

    private void btnCancelarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarTelActionPerformed

    private void btnGuardarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTelActionPerformed
        String idTaller = this.cmbTaller.getSelectedItem().toString();
        String idEmpleado = this.txtID.getText();
        String telefono = this.txtTelefonoNuevo.getText();

        try {
            TelefonoEmpleado guardarTelefono = new TelefonoEmpleado( telefono,idEmpleado, idTaller);
            tabla.guardarTelefono(guardarTelefono);
            JOptionPane.showMessageDialog(null, "Telefono ingresado con éxito.", "Exitosa", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        /*    
    try {
        ControladorTelefonoEmpleado controladorTelefonoEmpleado = new ControladorTelefonoEmpleado();
        TelefonoEmpleado telefonoEmpleado = new TelefonoEmpleado(idEmpleado, idTaller, telefono);
        
        controladorTelefonoEmpleado.guardarTelefono(telefonoEmpleado);
        
        JOptionPane.showMessageDialog(null, "Teléfono ingresado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al ingresar teléfono.", "Error", JOptionPane.ERROR_MESSAGE);
        System.err.println(ex.getMessage());
    }*/
    }//GEN-LAST:event_btnGuardarTelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTelefono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgBack;
    private javax.swing.JButton btnCancelarTel;
    private javax.swing.JButton btnGuardarTel;
    private javax.swing.JComboBox<String> cmbTaller;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCel1;
    private javax.swing.JLabel lblCel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTelefonoNuevo;
    // End of variables declaration//GEN-END:variables
}
