/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecarep.Views.Empleado;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mecarep.Controlers.ControladorEmpleado;
import mecarep.Controlers.Validaciones;
import mecarep.Views.PanelPrincipal;
import mecarep.Views.Vehiculos.RegistrarVehiculo;

/**
 *
 * @author USER
 */
public class ActEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form ActEmpleado
     */
    ControladorEmpleado tabla = new ControladorEmpleado();
    public ActEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        tabla.cargarIDEmpleadosEnComboBox(cmbId_emp);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        lblCel1 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        lblCel2 = new javax.swing.JLabel();
        cmbClienteTaller = new javax.swing.JComboBox<>();
        lblCel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnActualizar2 = new javax.swing.JButton();
        cmbId_emp = new javax.swing.JComboBox<>();
        bgBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Actualizar Empleado");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        lblCel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel.setForeground(new java.awt.Color(255, 255, 255));
        lblCel.setText("ID Empleado:");
        getContentPane().add(lblCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        lblCel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel1.setForeground(new java.awt.Color(255, 255, 255));
        lblCel1.setText("Actualizar: ");
        getContentPane().add(lblCel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));
        getContentPane().add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 180, -1));

        lblCel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel2.setForeground(new java.awt.Color(255, 255, 255));
        lblCel2.setText("Taller:");
        getContentPane().add(lblCel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        cmbClienteTaller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "T001", "T002" }));
        cmbClienteTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteTallerActionPerformed(evt);
            }
        });
        getContentPane().add(cmbClienteTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, -1));

        lblCel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel3.setForeground(new java.awt.Color(255, 255, 255));
        lblCel3.setText("Salario:");
        getContentPane().add(lblCel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(153, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Cancelar");
        btnRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 120, 30));

        btnActualizar2.setBackground(new java.awt.Color(0, 102, 204));
        btnActualizar2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizar2.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar2.setText("Actualizar");
        btnActualizar2.setToolTipText("");
        btnActualizar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 120, 30));

        cmbId_emp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------" }));
        getContentPane().add(cmbId_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 130, 20));

        bgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        getContentPane().add(bgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClienteTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteTallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClienteTallerActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar2ActionPerformed
        // TODO add your handling code here:
        Validaciones.validarDatosNumericos(txtSalario.getText());
        int salarioEntero = Integer.parseInt(txtSalario.getText());
        try {
            tabla.actualizarSalarioEmpleado(cmbId_emp.getSelectedItem().toString(), salarioEntero);
            JOptionPane.showMessageDialog(null, "Actualización Exitosa", "Empleado", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnActualizar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgBack;
    private javax.swing.JButton btnActualizar2;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbClienteTaller;
    private javax.swing.JComboBox<String> cmbId_emp;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCel1;
    private javax.swing.JLabel lblCel2;
    private javax.swing.JLabel lblCel3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
