/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mecarep.Views.Empleado;

import javax.swing.table.DefaultTableModel;
import mecarep.Controlers.ControladorEmpleado;


/**
 *
 * @author Usuario
 */
public class EmpleadoView extends javax.swing.JPanel {

    /**
     * Creates new form EmpleadoView
     */
    ControladorEmpleado ep;
    String idEmpleado;

    public EmpleadoView() {
        initComponents();
        ep = new ControladorEmpleado();
        ep.desplegarEmpleadosQuito(RegistrosEm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarEmpleado = new javax.swing.JButton();
        btnNuevoEmpleado = new javax.swing.JButton();
        btnActualizarEmpleado = new javax.swing.JButton();
        DatosE = new javax.swing.JScrollPane();
        RegistrosEm = new javax.swing.JTable();
        bgBack2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarEmpleado.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarEmpleado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.setToolTipText("");
        btnEliminarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });
        add(btnEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 120, 30));

        btnNuevoEmpleado.setBackground(new java.awt.Color(0, 102, 204));
        btnNuevoEmpleado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnNuevoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoEmpleado.setText("Nuevo");
        btnNuevoEmpleado.setToolTipText("");
        btnNuevoEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEmpleadoActionPerformed(evt);
            }
        });
        add(btnNuevoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, 30));

        btnActualizarEmpleado.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizarEmpleado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarEmpleado.setText("Actualizar");
        btnActualizarEmpleado.setToolTipText("");
        btnActualizarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEmpleadoActionPerformed(evt);
            }
        });
        add(btnActualizarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 120, 30));

        RegistrosEm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        RegistrosEm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrosEmMousePressed(evt);
            }
        });
        DatosE.setViewportView(RegistrosEm);

        add(DatosE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 680, 280));

        bgBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        add(bgBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        ep.eliminarEmpleado(idEmpleado);
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpleadoActionPerformed
        CreateUserEmpleado esp = new CreateUserEmpleado();
        esp.setVisible(true);
    }//GEN-LAST:event_btnNuevoEmpleadoActionPerformed

    private void btnActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEmpleadoActionPerformed
        ActEmpleado esp = new ActEmpleado();
        esp.setVisible(true);
    }//GEN-LAST:event_btnActualizarEmpleadoActionPerformed

    private void RegistrosEmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrosEmMousePressed
        DefaultTableModel modelo = (DefaultTableModel) RegistrosEm.getModel();
        int filaSeleccionada = RegistrosEm.getSelectedRow();
        if (filaSeleccionada != -1) {
            idEmpleado = modelo.getValueAt(filaSeleccionada, 0).toString();
        }
    }//GEN-LAST:event_RegistrosEmMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane DatosE;
    public javax.swing.JTable RegistrosEm;
    private javax.swing.JLabel bgBack2;
    private javax.swing.JButton btnActualizarEmpleado;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnNuevoEmpleado;
    // End of variables declaration//GEN-END:variables
}
