/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecarep.Views.Vehiculos;
import javax.swing.JOptionPane;
import mecarep.Controlers.ControladorVehiculo;
import mecarep.Models.Vehiculo;


/**
 *
 * @author Usuario
 */
public class RegistrarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarVehiculo
     */
    ControladorVehiculo v1 = new ControladorVehiculo();
    public RegistrarVehiculo() {
        initComponents();
        this.setLocationRelativeTo(null);
        v1.cargarNombresClientesEnComboBox(cmbPropietario);
        v1.cargarIDsSegurosEnComboBox(cmbSeguro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCel = new javax.swing.JLabel();
        lblCel2 = new javax.swing.JLabel();
        lblCel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        cmbTaller = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblCel5 = new javax.swing.JLabel();
        cmbPropietario = new javax.swing.JComboBox<>();
        lblCel3 = new javax.swing.JLabel();
        cmbSeguro = new javax.swing.JComboBox<>();
        fecha = new com.toedter.calendar.JDateChooser();
        bgBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel.setForeground(new java.awt.Color(255, 255, 255));
        lblCel.setText("Matricula:");
        jPanel1.add(lblCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        lblCel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel2.setForeground(new java.awt.Color(255, 255, 255));
        lblCel2.setText("Seguro:");
        jPanel1.add(lblCel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        lblCel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel4.setForeground(new java.awt.Color(255, 255, 255));
        lblCel4.setText("Propietario:");
        jPanel1.add(lblCel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        txtCedula.setToolTipText("");
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, -1));

        cmbTaller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "T001", "T002" }));
        jPanel1.add(cmbTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 130, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Registrar Vehiculo");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(153, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Cancelar");
        btnRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 120, 30));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 204));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 120, 30));

        lblCel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel5.setForeground(new java.awt.Color(255, 255, 255));
        lblCel5.setText("Taller:");
        jPanel1.add(lblCel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        cmbPropietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Max Grandote", "U001", "U002" }));
        jPanel1.add(cmbPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 130, -1));

        lblCel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel3.setForeground(new java.awt.Color(255, 255, 255));
        lblCel3.setText("Fecha Compra:");
        jPanel1.add(lblCel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        cmbSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "S001", "S002", "S003" }));
        jPanel1.add(cmbSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 130, -1));
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        bgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        jPanel1.add(bgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:        
        try {
            String nombre = cmbPropietario.getSelectedItem().toString().split("\\s+")[0];
            String apellido = cmbPropietario.getSelectedItem().toString().split("\\s+")[1];
            System.out.print(nombre+ ' ' + apellido);
            java.util.Date fechaUtil = fecha.getDate();
            java.sql.Date fechaSQL = new java.sql.Date(fechaUtil.getTime()); 
            Vehiculo vec1 = new Vehiculo(txtCedula.getText(), cmbTaller.getSelectedItem().toString(), nombre, apellido,cmbSeguro.getSelectedItem().toString(),fechaSQL);            
            v1.insertarVehiculo(vec1);
            JOptionPane.showMessageDialog(null, "Vehiculo Ingresado con éxito.", "Exitosa", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgBack;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbPropietario;
    private javax.swing.JComboBox<String> cmbSeguro;
    private javax.swing.JComboBox<String> cmbTaller;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCel2;
    private javax.swing.JLabel lblCel3;
    private javax.swing.JLabel lblCel4;
    private javax.swing.JLabel lblCel5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
