/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mecarep.Views.Vehiculos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import mecarep.Controlers.ControladorVehiculo;
import mecarep.Models.Vehiculo;

/**
 *
 * @author Usuario
 */
public class VehiculoView extends javax.swing.JPanel {

    /**
     * Creates new form VehiculoView
     */
    ControladorVehiculo v1;
    Vehiculo vecu;
    public VehiculoView() throws SQLException {        
        initComponents();
        v1 = new ControladorVehiculo();
        v1.mostrarVehiculosQuito(RegistrosVe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarVehiculo = new javax.swing.JButton();
        btnNuevoVehi = new javax.swing.JButton();
        Datos1 = new javax.swing.JScrollPane();
        RegistrosVe = new javax.swing.JTable();
        btnConsultaVertical = new javax.swing.JButton();
        bgBack2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarVehiculo.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarVehiculo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVehiculo.setText("Eliminar");
        btnEliminarVehiculo.setToolTipText("");
        btnEliminarVehiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVehiculoActionPerformed(evt);
            }
        });
        add(btnEliminarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 120, 30));

        btnNuevoVehi.setBackground(new java.awt.Color(0, 102, 204));
        btnNuevoVehi.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnNuevoVehi.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoVehi.setText("Nuevo");
        btnNuevoVehi.setToolTipText("");
        btnNuevoVehi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevoVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVehiActionPerformed(evt);
            }
        });
        add(btnNuevoVehi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, 30));

        RegistrosVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        RegistrosVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrosVeMousePressed(evt);
            }
        });
        Datos1.setViewportView(RegistrosVe);

        add(Datos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 690, 280));

        btnConsultaVertical.setBackground(new java.awt.Color(102, 102, 102));
        btnConsultaVertical.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultaVertical.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaVertical.setText("Consultar Matriculas");
        btnConsultaVertical.setToolTipText("");
        btnConsultaVertical.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultaVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaVerticalActionPerformed(evt);
            }
        });
        add(btnConsultaVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 160, 30));

        bgBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        add(bgBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVehiculoActionPerformed
        // TODO add your handling code here:
        if (vecu != null) {
            v1.eliminarVehiculo(vecu.getMatricula());
            try {
                v1.mostrarVehiculosQuito(RegistrosVe);
            } catch (SQLException ex) {
                Logger.getLogger(VehiculoView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarVehiculoActionPerformed

    private void btnNuevoVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVehiActionPerformed
        RegistrarVehiculo vec = new RegistrarVehiculo();
        vec.setVisible(true);
    }//GEN-LAST:event_btnNuevoVehiActionPerformed

    private void btnConsultaVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaVerticalActionPerformed
        // TODO add your handling code here:
        v1.mostrarVehiculosMatricula(RegistrosVe);
        btnNuevoVehi.setVisible(false);
        btnEliminarVehiculo.setVisible(false);
    }//GEN-LAST:event_btnConsultaVerticalActionPerformed

    private void RegistrosVeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrosVeMousePressed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) RegistrosVe.getModel();
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = RegistrosVe.getSelectedRow();
        // Comprobar si se ha seleccionado una fila válida
        if (filaSeleccionada != -1) {
            // Obtener los datos de la fila seleccionada y almacenarlos en variables
            String matricula = modelo.getValueAt(filaSeleccionada, 0).toString();
            String taller = modelo.getValueAt(filaSeleccionada, 1).toString();
            String nombre = modelo.getValueAt(filaSeleccionada, 2).toString();
            String apellido = modelo.getValueAt(filaSeleccionada, 3).toString();
            String seguro = modelo.getValueAt(filaSeleccionada, 4).toString();
            String fecha = modelo.getValueAt(filaSeleccionada, 5).toString();
            vecu = new Vehiculo(matricula, taller, nombre ,apellido, seguro, fecha);
        }            
    }//GEN-LAST:event_RegistrosVeMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane Datos1;
    public javax.swing.JTable RegistrosVe;
    private javax.swing.JLabel bgBack2;
    private javax.swing.JButton btnConsultaVertical;
    private javax.swing.JButton btnEliminarVehiculo;
    private javax.swing.JButton btnNuevoVehi;
    // End of variables declaration//GEN-END:variables
}
