-- Eliminar tabla TALLER_02 si existe
IF OBJECT_ID('TALLER_02') IS NOT NULL
DROP TABLE TALLER_02
GO

-- Crear tabla TALLER_02 con sus columnas y CONSTRAINT
CREATE TABLE TALLER_02 (
   ID_TALLER            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   NOMBRE_TALLER        CHAR(20) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   CIUDAD               CHAR(20) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   ID_DIRECTOR          CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
   CONSTRAINT PK_TALLER_02 PRIMARY KEY NONCLUSTERED (ID_TALLER)
)
GO

-- Eliminar tabla TELEFONOEMPLEADO_02 si existe
IF OBJECT_ID('TELEFONOEMPLEADO_02') IS NOT NULL
DROP TABLE TELEFONOEMPLEADO_02
GO

-- Crear tabla TELEFONOEMPLEADO_02 con sus columnas y CONSTRAINT
CREATE TABLE TELEFONOEMPLEADO_02 (
   TELEFONO             CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   ID_EMPLEADO          CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   ID_TALLER            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   CONSTRAINT PK_TELEFONOEMPLEADO_02 PRIMARY KEY NONCLUSTERED (TELEFONO, ID_EMPLEADO, ID_TALLER)
)
GO



-- Eliminar tabla REPARACIONES_02 si existe
IF OBJECT_ID('REPARACIONES_02') IS NOT NULL
DROP TABLE REPARACIONES_02
GO

-- Crear tabla REPARACIONES_02 con sus columnas y CONSTRAINT
CREATE TABLE REPARACIONES_02 (
   ID_REPARACION        CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   ID_TALLER            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   MATRICULA            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   FECHA_REPARACION     DATETIME NOT NULL,
   TIPO_REPARACION      CHAR(30) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   OBSERVACIONES        CHAR(30) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
   PRECIO_REPARACION    FLOAT NOT NULL,
   CONSTRAINT PK_REPARACIONES_02 PRIMARY KEY NONCLUSTERED (ID_REPARACION, MATRICULA, ID_TALLER)
)
GO



-- Eliminar tabla CLIENTE_02 si existe
IF OBJECT_ID('CLIENTE_02') IS NOT NULL
DROP TABLE CLIENTE_02
GO

-- Crear tabla CLIENTE_02 con sus columnas y CONSTRAINT
CREATE TABLE CLIENTE_02 (
   NOMBRE               CHAR(15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   APELLIDO             CHAR(15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   ID_TALLER            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   CIUDAD               CHAR(20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
   CEDULA               CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   CONSTRAINT PK_CLIENTE_02 PRIMARY KEY NONCLUSTERED (NOMBRE, APELLIDO, ID_TALLER)
)
GO

-- Eliminar tabla EMPLEADO_02 si existe
IF OBJECT_ID('EMPLEADO_02') IS NOT NULL
DROP TABLE EMPLEADO_02
GO

-- Crear tabla EMPLEADO_02 con sus columnas y CONSTRAINT
CREATE TABLE EMPLEADO_02 (
   ID_EMPLEADO          CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   ID_TALLER            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   CEDULA_EMPLEADO      CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   NOMBRE_EMPLEADO      CHAR(30) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   FECHA_INICIO_CONTRATO DATETIME NOT NULL,
   SALARIO              INT NOT NULL,
   CONSTRAINT PK_EMPLEADO_02 PRIMARY KEY NONCLUSTERED (ID_EMPLEADO, ID_TALLER)
)
GO


-- Eliminar tabla VEHICULO_02 si existe
IF OBJECT_ID('VEHICULO_02') IS NOT NULL
DROP TABLE VEHICULO_02
GO

-- Crear tabla VEHICULO_02 con sus columnas y CONSTRAINT
CREATE TABLE VEHICULO_02 (
   MATRICULA            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   ID_TALLER            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   NOMBRE               CHAR(15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   APELLIDO             CHAR(15) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   ID_SEGURO            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   FECHA_COMPRA         DATETIME NOT NULL,
   CONSTRAINT PK_VEHICULO_02 PRIMARY KEY NONCLUSTERED (MATRICULA, ID_TALLER)
)
GO


-- Eliminar tabla SEGUROS_02 si existe
IF OBJECT_ID('SEGUROS_02') IS NOT NULL
DROP TABLE SEGUROS_02
GO

-- Crear tabla SEGUROS_02 con sus columnas y CONSTRAINT
CREATE TABLE SEGUROS_02 (
   ID_SEGURO            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   ID_TALLER            CHAR(10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   NOMBRE_SEGURO        CHAR(25) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   TIPO_SEGURO          CHAR(25) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
   MONTO_COBERTURA      INT NOT NULL,
   CONSTRAINT PK_SEGUROS_02 PRIMARY KEY NONCLUSTERED (ID_SEGURO, ID_TALLER)
)
GO


sp_help TALLER_02