package mecarep.Views;

import mecarep.Views.Vehiculos.VehiculoView;
import mecarep.Views.Empleado.EmpleadoView;
import mecarep.Views.Cliente.ClienteView;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mecarep.Views.Seguros.SegurosView;
import mecarep.Views.Reparaciones.ReparacionesView;
import mecarep.Views.Telefonos.TelefonosView;

public class PanelPrincipal extends javax.swing.JFrame {

    public PanelPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReparaciones = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnSeguros = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        btnTelefEmp = new javax.swing.JButton();
        PanelControl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReparaciones.setBackground(new java.awt.Color(0, 0, 0));
        btnReparaciones.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnReparaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnReparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/reparar.png"))); // NOI18N
        btnReparaciones.setText("Reparaciones");
        btnReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReparacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReparaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 180, 60));

        btnClientes.setBackground(new java.awt.Color(0, 0, 0));
        btnClientes.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/costo-por-cliente-potencial.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 60));

        btnVehiculos.setBackground(new java.awt.Color(0, 0, 0));
        btnVehiculos.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/seguro-de-auto.png"))); // NOI18N
        btnVehiculos.setText("Vehiculos");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 60));

        btnSeguros.setBackground(new java.awt.Color(0, 0, 0));
        btnSeguros.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnSeguros.setForeground(new java.awt.Color(255, 255, 255));
        btnSeguros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/proteger.png"))); // NOI18N
        btnSeguros.setText("Seguros");
        btnSeguros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegurosActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeguros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 180, 60));

        btnEmpleados.setBackground(new java.awt.Color(0, 0, 0));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/empleado.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 60));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("MecaRepairs");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/logo-remove.png"))); // NOI18N
        jPanel1.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnTelefEmp.setBackground(new java.awt.Color(0, 0, 0));
        btnTelefEmp.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnTelefEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnTelefEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/phone_7135.png"))); // NOI18N
        btnTelefEmp.setText("Telefonos");
        btnTelefEmp.setMaximumSize(new java.awt.Dimension(135, 39));
        btnTelefEmp.setMinimumSize(new java.awt.Dimension(135, 39));
        btnTelefEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnTelefEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 180, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 500));

        javax.swing.GroupLayout PanelControlLayout = new javax.swing.GroupLayout(PanelControl);
        PanelControl.setLayout(PanelControlLayout);
        PanelControlLayout.setHorizontalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        PanelControlLayout.setVerticalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(PanelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 740, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        PanelControl.removeAll();
        PanelControl.revalidate();
        PanelControl.repaint();
        ClienteView p;
        p = new ClienteView(); //ES UN JPANEL
        p.setSize(1100, 840);
        p.setLocation(0, 0);
        PanelControl.add(p, BorderLayout.CENTER);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        PanelControl.removeAll();
        PanelControl.revalidate();
        PanelControl.repaint();
        VehiculoView p1;
        try {
            p1 = new VehiculoView(); //ES UN JPANEL
            p1.setSize(1100, 840);
            p1.setLocation(0, 0);
            PanelControl.add(p1, BorderLayout.CENTER);
        } catch (SQLException ex) {
            Logger.getLogger(PanelPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        PanelControl.removeAll();
        PanelControl.revalidate();
        PanelControl.repaint();
        EmpleadoView p1 = new EmpleadoView(); //ES UN JPANEL
        p1.setSize(1100, 840);
        p1.setLocation(0, 0);
        PanelControl.add(p1, BorderLayout.CENTER);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReparacionesActionPerformed
        PanelControl.removeAll();
        PanelControl.revalidate();
        PanelControl.repaint();
        ReparacionesView p1;
        try {
            p1 = new ReparacionesView(); //ES UN JPANEL
            p1.setSize(1100, 840);
            p1.setLocation(0, 0);
            PanelControl.add(p1, BorderLayout.CENTER);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReparacionesActionPerformed

    private void btnSegurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegurosActionPerformed
        PanelControl.removeAll();
        PanelControl.revalidate();
        PanelControl.repaint();
        SegurosView p1;
        try {
            p1 = new SegurosView(); //ES UN JPANEL
            p1.setSize(1100, 840);
            p1.setLocation(0, 0);
            PanelControl.add(p1, BorderLayout.CENTER);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSegurosActionPerformed

    private void btnTelefEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefEmpActionPerformed
        // TODO add your handling code here:
        PanelControl.removeAll();
        PanelControl.revalidate();
        PanelControl.repaint();
        TelefonosView p1 = new TelefonosView(); //ES UN JPANEL
        p1.setSize(1100, 840);
        p1.setLocation(0, 0);
        PanelControl.add(p1, BorderLayout.CENTER);
    }//GEN-LAST:event_btnTelefEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelControl;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnReparaciones;
    private javax.swing.JButton btnSeguros;
    private javax.swing.JButton btnTelefEmp;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
