package mecarep.Views.Reparaciones;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mecarep.Controlers.ControladorReparaciones;
import mecarep.Models.ReparacionesModel;

/**
 *
 * @author Usuario
 */
public class ReparacionesView extends javax.swing.JPanel {

    /**
     * Creates new form ReparacionesView
     */
    ControladorReparaciones rep;
    ReparacionesModel reps;

    public ReparacionesView() throws SQLException {
        initComponents();
        rep = new ControladorReparaciones();
        rep.desplegarReparacionesQuito(RegistrosRep);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarEmpleado = new javax.swing.JButton();
        btnNuevoReparacion = new javax.swing.JButton();
        dATOSR = new javax.swing.JScrollPane();
        RegistrosRep = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        txtMatricula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bgBack2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarEmpleado.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarEmpleado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.setToolTipText("");
        btnEliminarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });
        add(btnEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 120, 30));

        btnNuevoReparacion.setBackground(new java.awt.Color(0, 102, 204));
        btnNuevoReparacion.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnNuevoReparacion.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoReparacion.setText("Nuevo");
        btnNuevoReparacion.setToolTipText("");
        btnNuevoReparacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevoReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoReparacionActionPerformed(evt);
            }
        });
        add(btnNuevoReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, 30));

        RegistrosRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        RegistrosRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrosRepMousePressed(evt);
            }
        });
        dATOSR.setViewportView(RegistrosRep);

        add(dATOSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 670, 280));

        btnConsultar.setBackground(new java.awt.Color(153, 153, 153));
        btnConsultar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Buscar");
        btnConsultar.setToolTipText("");
        btnConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 110, 30));
        add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 130, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Matricula:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        bgBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        add(bgBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
        try {
            if (reps != null) {
                rep.eliminarReparacion(reps);
                rep.desplegarReparacionesQuito(RegistrosRep);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReparacionesView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnNuevoReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoReparacionActionPerformed
        Reparaciones ss = new Reparaciones();
        ss.setVisible(true);
    }//GEN-LAST:event_btnNuevoReparacionActionPerformed

    private void RegistrosRepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrosRepMousePressed
        DefaultTableModel modelo = (DefaultTableModel) RegistrosRep.getModel();
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = RegistrosRep.getSelectedRow();
        // Comprobar si se ha seleccionado una fila válida
        if (filaSeleccionada != -1) {

            String idRep = modelo.getValueAt(filaSeleccionada, 0).toString();
            String taller = modelo.getValueAt(filaSeleccionada, 1).toString();
            String matricula = modelo.getValueAt(filaSeleccionada, 2).toString();
            String fecha = modelo.getValueAt(filaSeleccionada, 3).toString();
            String tipo = modelo.getValueAt(filaSeleccionada, 4).toString();
            String observacion = modelo.getValueAt(filaSeleccionada, 5).toString();
            String precio = modelo.getValueAt(filaSeleccionada, 6).toString();
            reps = new ReparacionesModel(idRep, taller, matricula, fecha, tipo, observacion, precio);
        }
    }//GEN-LAST:event_RegistrosRepMousePressed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            // TODO add your handling code here:
            rep.desplegarReparacionesMatricula(RegistrosRep,txtMatricula.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable RegistrosRep;
    private javax.swing.JLabel bgBack2;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnNuevoReparacion;
    public javax.swing.JScrollPane dATOSR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables
}
