/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecarep.Views.Reparaciones;


import javax.swing.JOptionPane;
import mecarep.Controlers.ControladorReparaciones;
import mecarep.Controlers.Validaciones;
import mecarep.Models.ReparacionesModel;

/**
 *
 * @author USER
 */
public class Reparaciones extends javax.swing.JFrame {

    /**
     * Creates new form Reparaciones
     */
    ControladorReparaciones rep = new ControladorReparaciones();
    public Reparaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        lblCel1 = new javax.swing.JLabel();
        lblCel2 = new javax.swing.JLabel();
        lblCel3 = new javax.swing.JLabel();
        lblCel4 = new javax.swing.JLabel();
        lblCel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        txtIDReparacion = new javax.swing.JTextField();
        btnCancelarRep1 = new javax.swing.JButton();
        txtTipoRep = new javax.swing.JTextField();
        txtPrecioRep = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        btsGuardarRep = new javax.swing.JButton();
        btnCancelarRep = new javax.swing.JButton();
        cmbTaller = new javax.swing.JComboBox<>();
        lblCel6 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        bgBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Reparaciones");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        lblCel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel.setForeground(new java.awt.Color(255, 255, 255));
        lblCel.setText("ID Reparación:");
        getContentPane().add(lblCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        lblCel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel1.setForeground(new java.awt.Color(255, 255, 255));
        lblCel1.setText("Fecha Reparación:");
        getContentPane().add(lblCel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblCel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel2.setForeground(new java.awt.Color(255, 255, 255));
        lblCel2.setText("Matricula:");
        getContentPane().add(lblCel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        lblCel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel3.setForeground(new java.awt.Color(255, 255, 255));
        lblCel3.setText("Tipo Reparación: ");
        getContentPane().add(lblCel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        lblCel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel4.setForeground(new java.awt.Color(255, 255, 255));
        lblCel4.setText("Taller: ");
        getContentPane().add(lblCel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        lblCel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel5.setForeground(new java.awt.Color(255, 255, 255));
        lblCel5.setText("Observaciones: ");
        getContentPane().add(lblCel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 510, 100));

        txtIDReparacion.setEnabled(false);
        getContentPane().add(txtIDReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 140, -1));

        btnCancelarRep1.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelarRep1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCancelarRep1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarRep1.setText("Verificar");
        btnCancelarRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 120, -1));

        txtTipoRep.setEnabled(false);
        getContentPane().add(txtTipoRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 140, -1));

        txtPrecioRep.setEnabled(false);
        getContentPane().add(txtPrecioRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 140, -1));

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 160, -1));

        btsGuardarRep.setBackground(new java.awt.Color(0, 102, 204));
        btsGuardarRep.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btsGuardarRep.setForeground(new java.awt.Color(255, 255, 255));
        btsGuardarRep.setText("Guardar");
        btsGuardarRep.setEnabled(false);
        btsGuardarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsGuardarRepActionPerformed(evt);
            }
        });
        getContentPane().add(btsGuardarRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 110, 30));

        btnCancelarRep.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelarRep.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCancelarRep.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarRep.setText("Cancelar");
        btnCancelarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRepActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 110, 30));

        cmbTaller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------", "T001", "T002" }));
        cmbTaller.setEnabled(false);
        getContentPane().add(cmbTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        lblCel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel6.setForeground(new java.awt.Color(255, 255, 255));
        lblCel6.setText("Precio: ");
        getContentPane().add(lblCel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        fecha.setEnabled(false);
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, -1));

        bgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        getContentPane().add(bgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 618, 490));
        bgBack.getAccessibleContext().setAccessibleName("");
        bgBack.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRepActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarRepActionPerformed

    private void btsGuardarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsGuardarRepActionPerformed
        ReparacionesModel reparacion;
        try {
            java.util.Date fechaUtil = fecha.getDate();
            java.sql.Date fechaSQL = new java.sql.Date(fechaUtil.getTime()); 
            Validaciones.validarDatosNumericos(txtPrecioRep.getText());
            reparacion = new ReparacionesModel(txtIDReparacion.getText(), cmbTaller.getSelectedItem().toString(), txtMatricula.getText(),fechaSQL ,txtTipoRep.getText(),descripcion.getText(), Double.parseDouble(txtPrecioRep.getText()));
            rep.guardarReparaciones(reparacion);
            JOptionPane.showMessageDialog(null, "Reparación Ingresada con éxito.", "Exitosa", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();  
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }      
    }//GEN-LAST:event_btsGuardarRepActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void btnCancelarRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRep1ActionPerformed
        try {
            // TODO add your handling code here:
            if (rep.verificarMatriculaExistente(txtMatricula.getText())) {
                txtIDReparacion.setEnabled(true);
                txtTipoRep.setEnabled(true);
                fecha.setEnabled(true);
                txtPrecioRep.setEnabled(true);
                cmbTaller.setEnabled(true);
                btsGuardarRep.setEnabled(true);
            }else {
                JOptionPane.showMessageDialog(null, "Matrícula No Registrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelarRep1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reparaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgBack;
    private javax.swing.JButton btnCancelarRep;
    private javax.swing.JButton btnCancelarRep1;
    private javax.swing.JButton btsGuardarRep;
    private javax.swing.JComboBox<String> cmbTaller;
    private javax.swing.JTextArea descripcion;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCel1;
    private javax.swing.JLabel lblCel2;
    private javax.swing.JLabel lblCel3;
    private javax.swing.JLabel lblCel4;
    private javax.swing.JLabel lblCel5;
    private javax.swing.JLabel lblCel6;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtIDReparacion;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtPrecioRep;
    private javax.swing.JTextField txtTipoRep;
    // End of variables declaration//GEN-END:variables
}
