/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mecarep.Views.Seguros;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import mecarep.Controlers.ControladorSeguros;
import mecarep.Models.Seguro;

/**
 *
 * @author Usuario
 */
public class SegurosView extends javax.swing.JPanel {

    /**
     * Creates new form SegurosView
     */
    ControladorSeguros se;
    Seguro seguro;
    public SegurosView() throws SQLException {
        initComponents();
        se = new ControladorSeguros();
        se.desplegarSeguros01(RegistrosSeg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarEmpleado = new javax.swing.JButton();
        btnNuevoReparacion = new javax.swing.JButton();
        btnActualizaREp = new javax.swing.JButton();
        dATOSR = new javax.swing.JScrollPane();
        RegistrosSeg = new javax.swing.JTable();
        bgBack2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarEmpleado.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarEmpleado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnEliminarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.setToolTipText("");
        btnEliminarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });
        add(btnEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 120, 30));

        btnNuevoReparacion.setBackground(new java.awt.Color(0, 102, 204));
        btnNuevoReparacion.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnNuevoReparacion.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoReparacion.setText("Nuevo");
        btnNuevoReparacion.setToolTipText("");
        btnNuevoReparacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevoReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoReparacionActionPerformed(evt);
            }
        });
        add(btnNuevoReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, 30));

        btnActualizaREp.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizaREp.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnActualizaREp.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizaREp.setText("Actualizar");
        btnActualizaREp.setToolTipText("");
        btnActualizaREp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizaREp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaREpActionPerformed(evt);
            }
        });
        add(btnActualizaREp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 120, 30));

        RegistrosSeg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        RegistrosSeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrosSegMousePressed(evt);
            }
        });
        dATOSR.setViewportView(RegistrosSeg);

        add(dATOSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 490, 280));

        bgBack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        add(bgBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
        if (seguro != null){
            se.eliminarSeguros(seguro);
            try {
                se.desplegarSeguros01(RegistrosSeg);
            } catch (SQLException ex) {
                Logger.getLogger(SegurosView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnNuevoReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoReparacionActionPerformed
        Seguros seg = new Seguros();
        seg.setVisible(true);
    }//GEN-LAST:event_btnNuevoReparacionActionPerformed

    private void btnActualizaREpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaREpActionPerformed
        if (seguro != null) {
            ActSeguros seg = new ActSeguros(seguro);
            seg.setVisible(true);   
        }
    }//GEN-LAST:event_btnActualizaREpActionPerformed

    private void RegistrosSegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrosSegMousePressed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) RegistrosSeg.getModel();
        // Obtener el índice de la fila seleccionada
        int filaSeleccionada = RegistrosSeg.getSelectedRow();
        // Comprobar si se ha seleccionado una fila válida
        if (filaSeleccionada != -1) {
            // Obtener los datos de la fila seleccionada y almacenarlos en variables
            String idSeguro = modelo.getValueAt(filaSeleccionada, 0).toString();
            String taller = modelo.getValueAt(filaSeleccionada, 1).toString();
            String nombre = modelo.getValueAt(filaSeleccionada, 2).toString();
            String tipoSeguro = modelo.getValueAt(filaSeleccionada, 3).toString();
            String Monto = modelo.getValueAt(filaSeleccionada, 4).toString();
            seguro = new Seguro(idSeguro,taller, nombre, tipoSeguro, Integer.parseInt(Monto));
        }        
    }//GEN-LAST:event_RegistrosSegMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable RegistrosSeg;
    private javax.swing.JLabel bgBack2;
    private javax.swing.JButton btnActualizaREp;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnNuevoReparacion;
    public javax.swing.JScrollPane dATOSR;
    // End of variables declaration//GEN-END:variables
}
