/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecarep.Views.Seguros;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import mecarep.Controlers.ControladorSeguros;
import mecarep.Controlers.Validaciones;
import mecarep.Models.Seguro;

/**
 *
 * @author USER
 */
public class Seguros extends javax.swing.JFrame {

    /**
     * Creates new form Seguros
     */
    ControladorSeguros seg = new ControladorSeguros();
    public Seguros() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btsGuardarSeg = new javax.swing.JButton();
        btnCancelarSeg = new javax.swing.JButton();
        lblCel = new javax.swing.JLabel();
        lblCel1 = new javax.swing.JLabel();
        lblCel2 = new javax.swing.JLabel();
        lblCel3 = new javax.swing.JLabel();
        txtIDSeguro = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtNombreSeg = new javax.swing.JTextField();
        txtTipoSeg = new javax.swing.JTextField();
        cmbTallerR = new javax.swing.JComboBox<>();
        lblCel4 = new javax.swing.JLabel();
        bgBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Seguros");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        btsGuardarSeg.setBackground(new java.awt.Color(0, 102, 204));
        btsGuardarSeg.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btsGuardarSeg.setForeground(new java.awt.Color(255, 255, 255));
        btsGuardarSeg.setText("Guardar");
        btsGuardarSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsGuardarSegActionPerformed(evt);
            }
        });
        getContentPane().add(btsGuardarSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 110, 30));

        btnCancelarSeg.setBackground(new java.awt.Color(153, 0, 0));
        btnCancelarSeg.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCancelarSeg.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarSeg.setText("Cancelar");
        btnCancelarSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSegActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 110, 30));

        lblCel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel.setForeground(new java.awt.Color(255, 255, 255));
        lblCel.setText("ID Seguro: ");
        getContentPane().add(lblCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lblCel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel1.setForeground(new java.awt.Color(255, 255, 255));
        lblCel1.setText("Monto Cobertura: ");
        getContentPane().add(lblCel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        lblCel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel2.setForeground(new java.awt.Color(255, 255, 255));
        lblCel2.setText("Nombre:");
        getContentPane().add(lblCel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        lblCel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel3.setForeground(new java.awt.Color(255, 255, 255));
        lblCel3.setText("Taller");
        getContentPane().add(lblCel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        getContentPane().add(txtIDSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, -1));
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 110, -1));
        getContentPane().add(txtNombreSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 140, -1));
        getContentPane().add(txtTipoSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 150, -1));

        cmbTallerR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "T001", "T002" }));
        getContentPane().add(cmbTallerR, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 130, -1));

        lblCel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblCel4.setForeground(new java.awt.Color(255, 255, 255));
        lblCel4.setText("Tipo:");
        getContentPane().add(lblCel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        bgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mecarep/Views/img/bg-blue.jpg"))); // NOI18N
        getContentPane().add(bgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 618, 443));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSegActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarSegActionPerformed

    private void btsGuardarSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsGuardarSegActionPerformed
        try {
            Validaciones.validarDatosNumericos(txtMonto.getText());
            Seguro segu = new Seguro(txtIDSeguro.getText(),cmbTallerR.getSelectedItem().toString(), txtNombreSeg.getText(), txtTipoSeg.getText(),Integer.parseInt(txtMonto.getText()));
            seg.guardarSeguro(segu);
            JOptionPane.showMessageDialog(null, "Seguro Ingresado con éxito.", "Exitosa", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btsGuardarSegActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgBack;
    private javax.swing.JButton btnCancelarSeg;
    private javax.swing.JButton btsGuardarSeg;
    private javax.swing.JComboBox<String> cmbTallerR;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCel1;
    private javax.swing.JLabel lblCel2;
    private javax.swing.JLabel lblCel3;
    private javax.swing.JLabel lblCel4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtIDSeguro;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombreSeg;
    private javax.swing.JTextField txtTipoSeg;
    // End of variables declaration//GEN-END:variables
}
